language: ruby
rvm:
  - 2.5.1

before_script:
 - chmod +x publish.sh

script: publish.sh

branches:
  only:
  - develop

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build 